FROM whisper_server:latest
USER root
COPY "./" "./"
EXPOSE 5000

RUN chmod 777 run.sh

RUN pip3 install  -r ./requirements.txt   -i https://mirrors.aliyun.com/pypi/simple/ --extra-index-url  https://pypi.org/simple/
